### ISSUE TITLE
PANIC: unprotected error in call to Lua API (not enough memory)

### ISSUE THREAD

**Issue by LiuXinqi12** [swarth100/dynfu#1]
Hi, Thank your for your code. the code can work, but I don't know why the above error prompt occurs every time when i run it to frame number of 19. My computer has 16G of memory, but only 60% occupied when it runs. so i don't know how to resolve this problem. I tried to replace it to another computer, but the same problem arose. I look forward to your reply. Thank you!

**Comment by swarth100** [comment]
Hi @LiuXinqi12 
I'm sorry for the late reply.

I was talking to a fellow collaborator about this and unfortunately this is quite an old project for us and we've since moved on.

I strongly recommend you look on GitHub for alternative implementations. I know a number are available with various degrees of success in their results.

Wish you all the best!

**Comment by LiuXinqi12** [comment]
Hi Alberto Spina


Thank your reply. I read your project in detail and find it  not  involve the process of  Voxel fusion. I know this is very hard but i want to realize it.  i still not find the reason why caused this problem , but i try to optimize the energy function by cuda , which also will used in Voxel fusion at next step i though. I wonder if there is any suggestion or good project for me.  if have , thank your so mach !


Wish you all the best!




------------------ 原始邮件 ------------------
发件人: "Alberto Spina"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 晚上9:27
收件人: "swarth100/dynfu"<dynfu@noreply.github.com>;
抄送: "lxq."<759916769@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [swarth100/dynfu] PANIC: unprotected error in call to Lua API(not enough memory) (#1)




Hi @LiuXinqi12
 I'm sorry for the late reply.
 
I was talking to a fellow collaborator about this and unfortunately this is quite an old project for us and we've since moved on.
 
I strongly recommend you look on GitHub for alternative implementations. I know a number are available with various degrees of success in their results.
 
Wish you all the best!

**Comment by swarth100** [comment]
Hi @LiuXinqi12 

My main piece of advice is to redirect you to [sobfu](https://github.com/dgrzech/sobfu), which implements a slightly different paper, yet it offers an out-of-the-box maintained library.

The error comes from Opt, I have seen you have opened an issue with them as well, and it is likely due to the optimiser being unable to converge. With most scenes our implementation diverges pretty badly after around 20 frames, meaning that the solver will not be able to compute values for the various deformation nodes in the warpfield.

Again I strongly recommend to migrate into sobfu.
Both implementations branched off the same refactoring of kfusion. The have a similar source code layout, they share the same Cmake structure and build patterns. Sobfu is also much better tested than dynfu.

**Comment by LiuXinqi12** [comment]
Hi Alberto Spina
Thank you so much! I remember i used to star the sobfu ,but I didn't  read it.  I will see it as soon as possible.  If i make some progress, I will tell you at once.  Thank you so much again for your very helpful advice !  

Best wishes for you!





 
---Original---
